import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Image from 'next/image';
import { useAsa } from '../hooks/useAsa';
import { useEffect } from 'react';

export default function Home() {
  const { data, isLoading, error } = useAsa();

  useEffect(() => {
    console.log(data);
  }, [data]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Image
          src={require('../assets/Header Logo.svg')}
          alt="logo"
          width={150}
          height={62.94}
        />
        <button>ANALYSE ASAs</button>
      </header>
      <main>
        <div className={styles.heading}>
          <h1>List of Algorand Standard Assets on ASAlytics</h1>
        </div>
      </main>
    </div>
  );
}
